import type { Producer, Product, Order, Review } from "./types";

export const MOCK_PRODUCERS: Producer[] = [
  {
    id: "producer-1",
    userId: "user-1",
    name: "The Walled Garden Cheese",
    slug: "the-walled-garden-cheese",
    bio: "Handpicked artisan cheeses sourced directly from small-scale British farmhouses and caves. Rare clothbound cheddars, cave-aged blues, and seasonal soft cheeses — perfectly conditioned and delivered in temperature-controlled packaging.",
    story:
      "I spent fifteen years as a buyer for a large supermarket chain, watching extraordinary British cheesemakers get squeezed out because their cheeses were too complex, too seasonal, or too honest for a shelf life of six weeks. In 2015 I walked away and started The Walled Garden Cheese from a cold room in Matlock. We now source from thirty small-scale producers across the UK — people who make one or two cheeses exceptionally well and have no interest in scaling up. Some of our cheeses are made in quantities of fewer than 100 wheels per year. None of them are available in supermarkets. We visit every producer we work with before listing their cheese. We taste everything at maturity before dispatch. And we pack every order ourselves in temperature-controlled insulated boxes, with tasting notes for each cheese inside. We believe cheese is one of the most complex and rewarding foods on earth — and we want everyone to have access to the best of it.",
    location: "Matlock, Derbyshire",
    address: {
      line1: "The Old Cold Room, Bank Road",
      city: "Matlock",
      county: "Derbyshire",
      postcode: "DE4 3NF",
      country: "GB",
    },
    categories: ["cheese", "accompaniments"],
    images: {
      banner: "/images/hero.jpg",
      logo: "/images/cheddar.jpg",
    },
    status: "approved",
    commissionRate: 0,
    fulfilmentOptions: ["ship", "collect"],
    socialLinks: {
      instagram: "@walledgardencheese",
      facebook: "WalledGardenCheese",
    },
    rating: 4.9,
    reviewCount: 618,
    createdAt: new Date("2015-04-01"),
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    producerId: "producer-1",
    producerName: "The Walled Garden Cheese",
    producerSlug: "the-walled-garden-cheese",
    name: "Keen's Clothbound Cheddar (200g)",
    description:
      "One of the last traditional farmhouse cheddars made on a Somerset dairy farm using raw milk from their own Friesian herd. Matured for 15–18 months in cloth, turned by hand. Complex, nutty, and deeply savoury with a long finish. Cut to order from the wheel.",
    slug: "keens-clothbound-cheddar-200g",
    category: "cheese",
    price: 800,
    unit: "200g cut from the wheel",
    stock: 30,
    images: [
      "/images/cheddar.jpg",
    ],
    dietary: ["gluten-free", "vegetarian"],
    allergens: ["dairy"],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "prod-2",
    producerId: "producer-1",
    producerName: "The Walled Garden Cheese",
    producerSlug: "the-walled-garden-cheese",
    name: "Colston Bassett Stilton (200g)",
    description:
      "The benchmark for English blue cheese — made by a cooperative of local farms in Nottinghamshire since 1913. Creamy, rich, and piquant with a crumbly texture and generous blue veining. At its absolute best with a glass of tawny port or drizzled with our Derbyshire honey.",
    slug: "colston-bassett-stilton-200g",
    category: "cheese",
    price: 950,
    unit: "200g cut from the truckle",
    stock: 25,
    images: [
      "/images/stilton.jpg",
    ],
    dietary: ["gluten-free", "vegetarian"],
    allergens: ["dairy"],
    seasonal: false,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-05"),
  },
  {
    id: "prod-3",
    producerId: "producer-1",
    producerName: "The Walled Garden Cheese",
    producerSlug: "the-walled-garden-cheese",
    name: "Artisan Cheese Board Box",
    description:
      "Our signature selection — five cheeses handpicked for balance and contrast, with tasting notes for each. Typically includes a clothbound cheddar, a washed rind, a blue, a soft goat, and one seasonal surprise. Serves 6–8 as a cheese course. Changes seasonally.",
    slug: "artisan-cheese-board-box",
    category: "cheese",
    price: 3800,
    unit: "5 cheeses (serves 6–8)",
    stock: 20,
    images: [
      "/images/cheese-board.jpg",
    ],
    dietary: ["gluten-free", "vegetarian"],
    allergens: ["dairy"],
    seasonal: true,
    available: true,
    featured: true,
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "prod-4",
    producerId: "producer-1",
    producerName: "The Walled Garden Cheese",
    producerSlug: "the-walled-garden-cheese",
    name: "Tunworth (whole, 250g)",
    description:
      "England's answer to Camembert — a surface-ripened soft cheese made in Hampshire with raw cow's milk. Mushroomy, garlicky aroma with a liquid centre when perfectly ripe. Best eaten at room temperature, baked in its box with a splash of white wine and a sprig of thyme.",
    slug: "tunworth-250g",
    category: "cheese",
    price: 1100,
    unit: "whole 250g round",
    stock: 15,
    images: [
      "/images/tunworth.jpg",
    ],
    dietary: ["gluten-free", "vegetarian"],
    allergens: ["dairy"],
    seasonal: true,
    available: true,
    featured: true,
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "prod-5",
    producerId: "producer-1",
    producerName: "The Walled Garden Cheese",
    producerSlug: "the-walled-garden-cheese",
    name: "Aged Gouda (200g)",
    description:
      "A 24-month aged Gouda from a small Dutch family farm — amber coloured, crystalline, intensely sweet and complex. The protein crystals that form during long ageing give it a satisfying crunch. A gateway cheese for those who think they don't like strong flavours.",
    slug: "aged-gouda-200g",
    category: "cheese",
    price: 850,
    unit: "200g",
    stock: 28,
    images: [
      "/images/cheddar.jpg",
    ],
    dietary: ["gluten-free", "vegetarian"],
    allergens: ["dairy"],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "prod-6",
    producerId: "producer-1",
    producerName: "The Walled Garden Cheese",
    producerSlug: "the-walled-garden-cheese",
    name: "Wensleydale with Apricot (200g)",
    description:
      "A mild, crumbly Yorkshire Wensleydale from the original Hawes creamery, blended with pieces of sweet dried apricot. Fresh and milky with a gentle sweetness that makes it approachable for all palates. A classic on any cheese board.",
    slug: "wensleydale-apricot-200g",
    category: "cheese",
    price: 750,
    unit: "200g",
    stock: 35,
    images: [
      "/images/stilton.jpg",
    ],
    dietary: ["gluten-free", "vegetarian"],
    allergens: ["dairy"],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "prod-7",
    producerId: "producer-1",
    producerName: "The Walled Garden Cheese",
    producerSlug: "the-walled-garden-cheese",
    name: "Cheese & Chutney Hamper",
    description:
      "Three of our most popular cheeses — a clothbound cheddar, a Stilton, and a seasonal soft cheese — alongside two of our handmade chutneys: spiced pear and red onion marmalade. Beautifully packaged in a kraft box with tasting notes. A perfect gift.",
    slug: "cheese-chutney-hamper",
    category: "cheese",
    price: 4200,
    unit: "3 cheeses + 2 chutneys",
    stock: 18,
    images: [
      "/images/cheese-board.jpg",
    ],
    dietary: ["gluten-free", "vegetarian"],
    allergens: ["dairy"],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "prod-8",
    producerId: "producer-1",
    producerName: "The Walled Garden Cheese",
    producerSlug: "the-walled-garden-cheese",
    name: "Manchego Reserva (200g)",
    description:
      "12-month aged Manchego from a small family finca in La Mancha — a world away from the young, rubbery versions found in supermarkets. Firm, ivory paste with a complex flavour: buttery, nutty, and slightly sweet. Outstanding with quince paste and Marcona almonds.",
    slug: "manchego-reserva-200g",
    category: "cheese",
    price: 900,
    unit: "200g",
    stock: 22,
    images: [
      "/images/tunworth.jpg",
    ],
    dietary: ["gluten-free", "vegetarian"],
    allergens: ["dairy"],
    seasonal: false,
    available: true,
    createdAt: new Date("2024-03-01"),
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "rev-1",
    orderId: "order-1",
    consumerId: "consumer-1",
    consumerName: "Harriet J.",
    producerId: "producer-1",
    rating: 5,
    comment:
      "The cheese board box for Christmas was the highlight of the meal — genuinely some of the best cheese I've ever tasted. The tasting notes inside made it an experience, not just food. Every guest asked where I'd got it. Will be ordering again.",
    createdAt: new Date("2024-04-10"),
  },
  {
    id: "rev-2",
    orderId: "order-2",
    consumerId: "consumer-2",
    consumerName: "Patrick O.",
    producerId: "producer-1",
    rating: 5,
    comment:
      "The Keen's cheddar is on another level entirely. I've been buying cheddar my whole life and this is the first one that's made me stop and pay attention. The complexity, the finish — extraordinary. I ordered three pieces.",
    createdAt: new Date("2024-04-24"),
  },
  {
    id: "rev-3",
    orderId: "order-3",
    consumerId: "consumer-3",
    consumerName: "Anna C.",
    producerId: "producer-1",
    rating: 5,
    comment:
      "Ordered the Tunworth as a complete unknown and it arrived perfectly ripe. We baked it as recommended and it was astonishing — the whole kitchen smelt incredible and it tasted even better. The packaging and cold storage were also perfect.",
    createdAt: new Date("2024-05-08"),
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "order-demo-1",
    consumerId: "consumer-1",
    consumerName: "Demo Customer",
    items: [
      {
        productId: "prod-3",
        productName: "Artisan Cheese Board Box",
        producerId: "producer-1",
        producerName: "The Walled Garden Cheese",
        price: 3800,
        quantity: 1,
        unit: "5 cheeses (serves 6–8)",
        imageUrl: "/images/hero.jpg",
      },
      {
        productId: "prod-1",
        productName: "Keen's Clothbound Cheddar (200g)",
        producerId: "producer-1",
        producerName: "The Walled Garden Cheese",
        price: 800,
        quantity: 1,
        unit: "200g cut from the wheel",
        imageUrl: "/images/hero.jpg",
      },
    ],
    producerIds: ["producer-1"],
    status: "delivered",
    fulfilmentMethod: "delivery",
    deliveryAddress: {
      line1: "3 Crown Square",
      city: "Matlock",
      postcode: "DE4 3AT",
      country: "GB",
    },
    subtotal: 4600,
    commission: 0,
    deliveryFee: 395,
    total: 4995,
    stripePaymentIntentId: "pi_demo_cheese_001",
    createdAt: new Date("2024-04-12"),
    updatedAt: new Date("2024-04-13"),
  },
];
